### ISSUE TITLE
i can't compile

### ISSUE THREAD

**Issue by Goworlds** [rasta-mouse/SharpC2#6] opened 2023-01-16 07:15 UTC
/root/SharpC2/TeamServer/TeamServer.csproj : error NU1101: Unable to find package DonutCore. No packages exist with this id in source(s): nuget.org
  Failed to restore /root/SharpC2/TeamServer/TeamServer.csproj (in 7.24 min)

**Comment by rasta-mouse** [comment] 2023-01-16 10:28
Duplicate of #1

**Closed as completed by rasta-mouse** 2023-01-16 10:28 UTC
